apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: cdstudio.atlas-spring-microservice
  description: Atlas App Microservice
  tags:
    - springboot
    - java
  annotations:
    github.com/project-slug: Danone-sandbox-MFA-testing/cdstudio.atlas-spring-api
    sonarqube.org/project-key: Danone-sandbox-MFA-testing_test-repo-with-dependabot-vuln
  links:
    - url: https://azure.microsoft.com/en-us/products/functions
      title: Azure functions
spec:
  type: microservice
  lifecycle: experimental
  system: cdstudio.atlas-app
  owner: cloud-dev-studio
 
